spring.application.name=quanlysinhvien_Springboot

spring.datasource.url=jdbc:postgresql://localhost:5432/quanlysinhvien
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

jwt.secret=qlsv-springboot-secret-key-demo-demo-demo-demo-123456789
jwt.expiration=86400000